### ISSUE TITLE
Uses Fabric internals

### ISSUE THREAD

**Issue by TropheusJ** [omoflop/MoreBlockPredicates#14]
MBP uses loader's internal logger [here](https://github.com/omoflop/MoreBlockPredicates/blob/1b041fb7ef1ead88447fd89a4958b42ec45c5d16/src/main/java/mod/omoflop/mbp/MBPMixinPlugin.java#L24).
This will make the message appear to come from loader, and causes the game to crash on quilt.
All mods should make their own logger, as done [in the example mod](https://github.com/FabricMC/fabric-example-mod/blob/3935c0f71dbd07317861c521502721bd9c773735/src/main/java/net/fabricmc/example/ExampleMod.java#L11).

**Comment by TropheusJ** [comment]
Additionally, the model loading registry *impl* is used instead of the API [here](https://github.com/omoflop/MoreBlockPredicates/blob/1b041fb7ef1ead88447fd89a4958b42ec45c5d16/src/main/java/mod/omoflop/mbp/client/MBPClient.java#L25).

**Comment by TropheusJ** [comment]
The logger is also used across several other classes.

**Comment by omoflop** [comment]
Fixed
