### ISSUE TITLE
Incompatible with Iris 1.6.2

### ISSUE THREAD

**Issue by NaiNonTH** [omoflop/MoreBlockPredicates#15]
## Description
After seconds of loading, the game quickly pops up and stops without an error log.

## Logs
[latest.log](https://github.com/omoflop/MoreBlockPredicates/files/11399529/latest.log)

**Comment by omoflop** [comment]
Looks like a conflict with a sodium mixin. Closing for now, please create a new issue if this is still happening on the latest version.
