### ISSUE TITLE
[1.19.4, no sodium] Model of placed blocks doesnt change

### ISSUE THREAD

**Issue by Enchanted-Games** [omoflop/MoreBlockPredicates#16]
Fabric Loader: 0.14.21
Fabric API: 0.83.0
MBP: 1.5
(these are the only mods I have installed)

This is the resourcepack i'm using for demonstration
[sand-test-mpb.zip](https://github.com/omoflop/MoreBlockPredicates/files/11681614/sand-test-mpb.zip)

Expected Result:
Sand uses the minecraft:stone model when an air block is above it.

Actual Result:
Falling Sand blocks, Sand items and Sand block particles change to that of stone as expected, but the actual sand block placed in the world does not change.

Log 
[latest.log](https://github.com/omoflop/MoreBlockPredicates/files/11681644/latest.log)

**Comment by omoflop** [comment]
This is a known issue.
Disable "always tesselate block models" in config/fabric/indigo-renderer.properties
